# Generated by Django 4.1.7 on 2023-03-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_dish_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disliked_dishes',
            field=models.ManyToManyField(blank=True, related_name='disliked_dishs', to='food.dish', verbose_name='Дизлайкнутые блюда'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_dishes',
            field=models.ManyToManyField(blank=True, related_name='liked_dishs', to='food.dish', verbose_name='Лайкнутые блюда'),
        ),
    ]
