# Generated by Django 4.1.7 on 2023-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, verbose_name='рецепт'),
        ),
        migrations.DeleteModel(
            name='DishItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
