# Generated by Django 4.1.7 on 2023-03-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_dish_recipe_delete_dishitem_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория блюд',
                'verbose_name_plural': 'категории блюд',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='food.dishcategory', verbose_name='категория'),
        ),
    ]
