# Generated by Django 4.1.7 on 2023-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='food.meal', verbose_name='приемы пищи'),
        ),
    ]
