# Generated by Django 4.1.7 on 2023-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
